export const data = [
    {
        nombre: 'Star Wars #25',
        categoria: 'comics',
        cover: '../assets/img/covers/starwars-25.jpg',
        editorial: 'Marvel Comics',
        nuevo: true,
        precio: 300,
        stock: 16,
    },
    {
        nombre: "X-Men '92 - House of XCII #1",
        categoria: 'comics',
        cover: '../assets/img/covers/xmen92-1.jpg',
        editorial: 'Marvel Comics',
        nuevo: true,
        precio: 250,
        stock: 12,
    },
    {
        nombre: "SPAWN - Volumen 331",
        categoria: 'comics',
        cover: '../assets/img/covers/spwan-331.jpg',
        editorial: 'Image Comics',
        nuevo: true,
        precio: 340,
        stock: 5,
    },
    {
        nombre: "Batman Beyond - Neo Year #1",
        categoria: 'comics',
        cover: '../assets/img/covers/batman-beyond1.jpg',
        editorial: 'DC Comics',
        nuevo: true,
        precio: 340,
        stock: 10,
    },
    {
        nombre: "Fantastic Four - Volumen 45",
        categoria: 'comics',
        cover: '../assets/img/covers/fantasticfour-45.jpg',
        editorial: 'Marvel Comics',
        nuevo: true,
        precio: 280,
        stock: 14,
    },
    {
        nombre: "Ghost Rider - Volumen 5",
        categoria: 'comics',
        cover: '../assets/img/covers/ghostrider-5.jpg',
        editorial: 'Marvel Comics',
        nuevo: true,
        precio: 280,
        stock: 14,
    },
    {
        nombre: "Green Lantern - Volumen 12",
        categoria: 'comics',
        cover: '../assets/img/covers/greenlantern-12.jpg',
        editorial: 'DC Comics',
        nuevo: true,
        precio: 260,
        stock: 5,
    },
    {
        nombre: "Iron Man - Volumen 21",
        categoria: 'comics',
        cover: '../assets/img/covers/ironman-21.jpg',
        editorial: 'Marvel Comics',
        nuevo: true,
        precio: 360,
        stock: 6,
    },
    {
        nombre: "Demon Slayer - Volumen 10",
        categoria: 'mangas',
        cover: '../assets/img/covers/demonslayer-10.jpg',
        editorial: 'Viz Media',
        nuevo: false,
        precio: 240,
        stock: 0,
    },
    {
        nombre: "Death Note - Short Stories",
        categoria: 'mangas',
        cover: '../assets/img/covers/deathnote-ss.jpg',
        editorial: 'Viz Media',
        nuevo: true,
        precio: 380,
        stock: 12,
    },
    {
        nombre: "Call of the Night - Volumen 7",
        categoria: 'mangas',
        cover: '../assets/img/covers/callofthenight-7.jpg',
        editorial: 'Viz Media',
        nuevo: true,
        precio: 400,
        stock: 4,
    }
]